name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ["2.5", "2.6", "2.7", "3.0"]
        gemfile: ["4.2", "5.2", "6.0", "6.1"]
        postgres_version: [9, 10, 11, 12]
        exclude:
          - { gemfile: "4.2", ruby_version: "2.7" }
          - { gemfile: "4.2", ruby_version: "3.0" }
          - { gemfile: "5.2", ruby_version: "3.0" }
    services:
      db:
        image: postgres:${{ matrix.postgres_version }}
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Test with Rake
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        BUNDLE_GEMFILE: spec/gemfiles/Gemfile.${{ matrix.gemfile }}
      run: |
        sudo apt-get -yqq install libpq-dev postgresql-client
        createdb que-test
        gem install bundler
        bundle install --jobs 4 --retry 3
        USE_RAILS=true bundle exec rake test
        bundle exec rake test
